2025-03-09 20:54:08,936 INFO    Thread-247 (_run_job):17292 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_205408-226g08xu\logs\debug.log
2025-03-09 20:54:08,936 INFO    Thread-247 (_run_job):17292 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_205408-226g08xu\logs\debug-internal.log
2025-03-09 20:54:08,936 INFO    Thread-247 (_run_job):17292 [wandb_init.py:init():761] calling init triggers
2025-03-09 20:54:08,936 INFO    Thread-247 (_run_job):17292 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 16, 'hiddenLayer_Size': 32, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'adam', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 32, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 20:54:08,936 INFO    Thread-247 (_run_job):17292 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 20:54:08,938 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/226g08xu
2025-03-09 20:54:08,939 ERROR   Thread-247 (_run_job):17292 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 20:54:08,939 INFO    Thread-247 (_run_job):17292 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 20:54:08,939 INFO    Thread-247 (_run_job):17292 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 20:54:08,940 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 20:54:08,940 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_restore():2322] restore
2025-03-09 20:54:08,940 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_restore():2328] restore done
2025-03-09 20:54:10,972 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 20:54:10,972 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 20:54:10,972 INFO    Thread-247 (_run_job):17292 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 20:54:10,977 ERROR   MainThread:17292 [pyagent.py:_run_jobs_from_queue():234] Run 226g08xu errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_17292\2599373716.py", line 34, in sweep_hyperParameters
    model = FeedforwardNeuralNetwork(x_train.shape[0], hiddenLayer_size, y_train.shape[0])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_17292\3812825710.py", line 21, in __init__
    for layer_size in hidden_layers:
                      ^^^^^^^^^^^^^
TypeError: 'int' object is not iterable

2025-03-09 20:54:10,977 ERROR   MainThread:17292 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
